spring:
  datasource:
    url: jdbc:mysql://localhost:3306/population_stats_db
    username: admin
    password: admin
  jpa:
    properties:
      hibernate:
        ddl-auto: update
        dialect: org.hibernate.dialect.MySQL8Dialect
        jdbc:
          lob:
            non_contextual_creation: true
  liquibase:
    change-log: "classpath:/liquibase/db-changelog-master.yaml"
server:
  port: 8080

springdoc:
  api-docs:
    path: /api-docs
